swagger: '2.0'

# 文档信息
info:
  description: API description in Markdown.
  version: 1.0.0
  title: Gateway API

  contact:
    email: admin@admin.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

#host: wheel.com
# 路径前缀
basePath: api/v1/

#标签
tags:
- name: user

schemes:
- http

paths:
  /users/query/{userId}:
    get:
      tags:
      - "user"
      summary: "根据用户ID获取用户信息。"
      description: "ID为正整数"
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "需要获取用户的ID值"
        required: true
        type: "integer"
        maximum: 10
        minimum: 1
        format: "int32"
      responses:
        200:
          description: "操作成功"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "错误的ID"
        404:
          description: "用户不存在"

definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "编号"
      name:
        type: "string"
        description: "名称"
      complete:
        type: "boolean"
        default: false